# Generated by Django 5.0.6 on 2024-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='established_date',
        ),
    ]
