# Generated by Django 5.0.6 on 2024-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_image_carimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
