# Generated by Django 5.0.6 on 2024-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
