# Generated by Django 5.0.6 on 2024-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carimages_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
