# Generated by Django 5.0.6 on 2024-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_created_at_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='brandmodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='unique_brand_model'),
        ),
    ]
